services:
  ui:
    image: beeswarm_lb
    build:
      context: ./ui
      dockerfile: ./Dockerfile
    container_name: beeswarm_ui
    ports:
      - "8600:3000"
    restart: always
    mem_limit: 1g
    cpus: "2.0"

  api:
    image: beeswarm_lb_api
    build:
      context: ./api
      dockerfile: ./Dockerfile
    container_name: beeswarm_api
    ports:
      - "8601:8080"
    restart: always
    # env_file: .env
    mem_limit: 1g
    cpus: "2.0"
